#!/usr/local/bin/python

################################################################################
# Author:     Thomas D'haenens
# License:    GPL-3.0
# Link:       https://github.com/BENEATLY/neat-community/
# Contact:    https://neatly.be/
################################################################################


# IMPORT: Standard Modules
import sys                                                                                      # System Lib
import ujson                                                                                    # UJSON Lib


# FUNCTION: Read JSON File (No Logging)
def readJSONFile(file):
    with open(file, encoding='utf-8') as content:
        return ujson.load(content)


# CONFIGURATION: Determine Installation Location
locationConfig = readJSONFile('/etc/neatly/base/location.json')

# CONFIGURATION: Add Current Path to Default Python Paths
sys.path.append(locationConfig['lib'])


# IMPORT: Custom Modules
from basic import *                                                                             # Actions Lib


# QUERY: Drop Alembic Versioning Table
[dropOut, dropStatus] = shHandler(handler=shPasswordHandler(sys.sharedConfig.db['connection']['password']), noLog=True)(sys.executables.dbClient)('-U', sys.sharedConfig.db['connection']['userName'], sys.sharedConfig.db['connection']['db'], '-c', 'DROP TABLE "alembic_version";')

# PRINT: Drop Status
print('-> Dropped migration table')

# FILE: Remove Historic Migration Files
for root, dirs, files in os.walk('/var/lib/neatly/base/migrations/versions/'):
    [os.unlink(os.path.join(root, f)) for f in files]
    [shutil.rmtree(os.path.join(root, d)) for d in dirs]

# PRINT: Remove Migration Files
print('-> Removed historical migration files')
