#!/usr/local/bin/python

################################################################################
# Author:     Thomas D'haenens
# License:    GPL-3.0
# Link:       https://github.com/BENEATLY/neat-community/
# Contact:    https://neatly.be/
################################################################################


# IMPORT: Standard Modules
import sys                                                                                      # System Lib
import ujson                                                                                    # UJSON Lib


# FUNCTION: Read JSON File (No Logging)
def readJSONFile(file):
    with open(file, encoding='utf-8') as content:
        return ujson.load(content)


# CONFIGURATION: Determine Installation Location
locationConfig = readJSONFile('/etc/neatly/base/location.json')

# CONFIGURATION: Add Current Path to Default Python Paths
sys.path.append(locationConfig['lib'])


# IMPORT: Custom Modules
from basic import shInteractiveHandler, shInteractivePasswordHandler                            # Actions Lib


# SHELL: Start Interactive DB Connection via PSQL
passwordHandler = shInteractivePasswordHandler(password=sys.sharedConfig.db['connection']['password'], timeout=5)
shInteractiveHandler(handler=passwordHandler, noLog=True)(sys.executables.dbClient)("-U", sys.sharedConfig.db['connection']['userName'], sys.sharedConfig.db['connection']['db'])
